import { A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Vertical timeline with dots and date column */
export function buildTimelineResume(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const pad = 48;
  const lineX = pad + 100;
  const contentX = lineX + 32;
  const contentW = A4_WIDTH - contentX - pad;

  return [
    el({
      id: "name",
      type: "text",
      x: pad,
      y: 40,
      width: A4_WIDTH - pad * 2,
      height: 40,
      content: SAMPLE.name,
      style: {
        fontSize: 30,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "title",
      type: "text",
      x: pad,
      y: 84,
      width: A4_WIDTH - pad * 2,
      height: 22,
      content: SAMPLE.title,
      style: { fontSize: 14, color: theme.accent, fontFamily: fonts.body },
    }),
    el({
      id: "contact",
      type: "text",
      x: pad,
      y: 112,
      width: A4_WIDTH - pad * 2,
      height: 18,
      content: SAMPLE.contact,
      style: { fontSize: 10, color: theme.muted, fontFamily: fonts.body },
    }),
    el({
      id: "summary",
      type: "text",
      x: pad,
      y: 148,
      width: A4_WIDTH - pad * 2,
      height: 52,
      content: SAMPLE.summary,
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "timeline-label",
      type: "text",
      x: pad,
      y: 220,
      width: 200,
      height: 20,
      content: "Career Timeline",
      style: {
        fontSize: 13,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "timeline-line",
      type: "section",
      x: lineX,
      y: 256,
      width: 3,
      height: 420,
      content: "",
      style: { background: theme.accent, borderRadius: 2, opacity: 0.5 },
    }),
    el({
      id: "dot-1",
      type: "section",
      x: lineX - 6,
      y: 268,
      width: 15,
      height: 15,
      content: "",
      style: { background: theme.primary, borderRadius: 999 },
    }),
    el({
      id: "date-1",
      type: "text",
      x: pad,
      y: 262,
      width: 88,
      height: 28,
      content: "2022\nPresent",
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.body,
        textAlign: "right",
        lineHeight: 1.3,
      },
    }),
    el({
      id: "job-1",
      type: "text",
      x: contentX,
      y: 258,
      width: contentW,
      height: 80,
      content: "Product Lead — SmartCV.AZ\n• Scaled to 10k+ users\n• +34% conversion via UX",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.55 },
    }),
    el({
      id: "dot-2",
      type: "section",
      x: lineX - 6,
      y: 368,
      width: 15,
      height: 15,
      content: "",
      style: { background: theme.accent, borderRadius: 999 },
    }),
    el({
      id: "date-2",
      type: "text",
      x: pad,
      y: 362,
      width: 88,
      height: 28,
      content: "2018\n2022",
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.body,
        textAlign: "right",
        lineHeight: 1.3,
      },
    }),
    el({
      id: "job-2",
      type: "text",
      x: contentX,
      y: 358,
      width: contentW,
      height: 80,
      content: "Project Manager — TechCorp\n• Led 12-person team\n• $2M initiative delivered",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.55 },
    }),
    el({
      id: "dot-3",
      type: "section",
      x: lineX - 6,
      y: 468,
      width: 15,
      height: 15,
      content: "",
      style: { background: theme.muted, borderRadius: 999 },
    }),
    el({
      id: "date-3",
      type: "text",
      x: pad,
      y: 462,
      width: 88,
      height: 28,
      content: "2014\n2018",
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.body,
        textAlign: "right",
        lineHeight: 1.3,
      },
    }),
    el({
      id: "job-3",
      type: "text",
      x: contentX,
      y: 458,
      width: contentW,
      height: 80,
      content: "Business Analyst — FinGroup\n• Process optimization\n• Cross-team analytics",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.55 },
    }),
    el({
      id: "edu-label",
      type: "text",
      x: pad,
      y: 700,
      width: 200,
      height: 20,
      content: "Education",
      style: {
        fontSize: 13,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: pad,
      y: 728,
      width: A4_WIDTH - pad * 2,
      height: 72,
      content: SAMPLE.education,
      sectionType: "education",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.55 },
    }),
    el({
      id: "skills-label",
      type: "text",
      x: pad,
      y: 820,
      width: 120,
      height: 18,
      content: "Skills",
      style: {
        fontSize: 13,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "skills",
      type: "text",
      x: pad,
      y: 848,
      width: A4_WIDTH - pad * 2,
      height: 64,
      content: SAMPLE.skills.replace(/\n/g, "  ·  "),
      sectionType: "skills",
      style: { fontSize: 10, color: theme.muted, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
  ];
}
