import { A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Apple-style massive whitespace, light typography */
export function buildAppleMinimal(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const pad = 80;
  const w = A4_WIDTH - pad * 2;

  return [
    el({
      id: "name",
      type: "text",
      x: pad,
      y: 120,
      width: w,
      height: 56,
      content: SAMPLE.name,
      style: {
        fontSize: 42,
        fontWeight: 600,
        color: theme.text,
        fontFamily: fonts.heading,
        letterSpacing: -1.5,
        lineHeight: 1.05,
      },
    }),
    el({
      id: "title",
      type: "text",
      x: pad,
      y: 184,
      width: w,
      height: 28,
      content: SAMPLE.title,
      style: {
        fontSize: 17,
        fontWeight: 400,
        color: theme.muted,
        fontFamily: fonts.body,
        letterSpacing: -0.3,
      },
    }),
    el({
      id: "contact",
      type: "text",
      x: pad,
      y: 232,
      width: w,
      height: 20,
      content: SAMPLE.contact,
      style: {
        fontSize: 11,
        color: theme.muted,
        fontFamily: fonts.body,
        opacity: 0.7,
      },
    }),
    el({
      id: "spacer-rule",
      type: "section",
      x: pad,
      y: 280,
      width: 32,
      height: 1,
      content: "",
      style: { background: theme.muted, opacity: 0.3 },
    }),
    el({
      id: "summary",
      type: "text",
      x: pad,
      y: 320,
      width: w * 0.75,
      height: 72,
      content: SAMPLE.summary,
      style: {
        fontSize: 13,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.75,
        fontWeight: 400,
      },
    }),
    el({
      id: "exp-label",
      type: "text",
      x: pad,
      y: 440,
      width: w,
      height: 22,
      content: "Experience",
      style: {
        fontSize: 12,
        fontWeight: 600,
        color: theme.muted,
        fontFamily: fonts.body,
        letterSpacing: 0,
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: pad,
      y: 476,
      width: w * 0.82,
      height: 180,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: {
        fontSize: 12,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.8,
        fontWeight: 400,
      },
    }),
    el({
      id: "edu-label",
      type: "text",
      x: pad,
      y: 680,
      width: w,
      height: 22,
      content: "Education",
      style: {
        fontSize: 12,
        fontWeight: 600,
        color: theme.muted,
        fontFamily: fonts.body,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: pad,
      y: 716,
      width: w * 0.7,
      height: 72,
      content: SAMPLE.education,
      sectionType: "education",
      style: {
        fontSize: 12,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.75,
      },
    }),
  ];
}
