import { A4_HEIGHT, A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Glassmorphism — gradient bg, floating blur cards */
export function buildGlassmorphism(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  return [
    el({
      id: "bg-gradient",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: A4_HEIGHT,
      content: "",
      locked: true,
      style: { background: theme.background, borderRadius: 0 },
    }),
    el({
      id: "orb-1",
      type: "section",
      x: -60,
      y: 80,
      width: 200,
      height: 200,
      content: "",
      style: {
        background: theme.primary,
        borderRadius: 999,
        opacity: 0.35,
      },
    }),
    el({
      id: "orb-2",
      type: "section",
      x: 600,
      y: 400,
      width: 260,
      height: 260,
      content: "",
      style: {
        background: theme.accent,
        borderRadius: 999,
        opacity: 0.25,
      },
    }),
    el({
      id: "header-card",
      type: "section",
      x: 48,
      y: 48,
      width: A4_WIDTH - 96,
      height: 140,
      content: "",
      style: {
        background: "rgba(255,255,255,0.25)",
        border: "1px solid rgba(255,255,255,0.4)",
        borderRadius: 20,
        boxShadow: "0 8px 32px rgba(31,38,135,0.15)",
        padding: 24,
      },
    }),
    el({
      id: "avatar",
      type: "image",
      x: 72,
      y: 72,
      width: 88,
      height: 88,
      content: "",
      style: {
        background: "rgba(255,255,255,0.5)",
        borderRadius: 999,
        border: "2px solid rgba(255,255,255,0.6)",
      },
    }),
    el({
      id: "name",
      type: "text",
      x: 180,
      y: 72,
      width: 520,
      height: 36,
      content: SAMPLE.name,
      style: {
        fontSize: 26,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "title",
      type: "text",
      x: 180,
      y: 112,
      width: 400,
      height: 22,
      content: SAMPLE.title,
      style: { fontSize: 13, color: theme.muted, fontFamily: fonts.body },
    }),
    el({
      id: "contact",
      type: "text",
      x: 180,
      y: 140,
      width: 480,
      height: 18,
      content: SAMPLE.contact,
      style: { fontSize: 10, color: theme.muted, fontFamily: fonts.body, opacity: 0.85 },
    }),
    el({
      id: "about-card",
      type: "section",
      x: 48,
      y: 212,
      width: 360,
      height: 120,
      content: "",
      style: {
        background: "rgba(255,255,255,0.2)",
        border: "1px solid rgba(255,255,255,0.35)",
        borderRadius: 16,
        boxShadow: "0 4px 24px rgba(31,38,135,0.1)",
      },
    }),
    el({
      id: "summary",
      type: "text",
      x: 64,
      y: 228,
      width: 328,
      height: 88,
      content: SAMPLE.summary,
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "skills-card",
      type: "section",
      x: 428,
      y: 212,
      width: 318,
      height: 120,
      content: "",
      style: {
        background: "rgba(255,255,255,0.18)",
        border: "1px solid rgba(255,255,255,0.3)",
        borderRadius: 16,
      },
    }),
    el({
      id: "skills",
      type: "text",
      x: 444,
      y: 232,
      width: 286,
      height: 80,
      content: SAMPLE.skills,
      sectionType: "skills",
      style: { fontSize: 10, color: theme.text, fontFamily: fonts.body, lineHeight: 1.7 },
    }),
    el({
      id: "exp-card",
      type: "section",
      x: 48,
      y: 356,
      width: A4_WIDTH - 96,
      height: 240,
      content: "",
      style: {
        background: "rgba(255,255,255,0.22)",
        border: "1px solid rgba(255,255,255,0.38)",
        borderRadius: 20,
        boxShadow: "0 8px 32px rgba(31,38,135,0.12)",
      },
    }),
    el({
      id: "exp-label",
      type: "text",
      x: 72,
      y: 376,
      width: 200,
      height: 20,
      content: "Experience",
      style: {
        fontSize: 13,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: 72,
      y: 404,
      width: A4_WIDTH - 144,
      height: 172,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "edu-card",
      type: "section",
      x: 48,
      y: 616,
      width: 400,
      height: 100,
      content: "",
      style: {
        background: "rgba(255,255,255,0.2)",
        border: "1px solid rgba(255,255,255,0.35)",
        borderRadius: 16,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: 64,
      y: 636,
      width: 368,
      height: 64,
      content: SAMPLE.education,
      sectionType: "education",
      style: { fontSize: 10, color: theme.text, fontFamily: fonts.body, lineHeight: 1.5 },
    }),
  ];
}
