import { A4_HEIGHT, A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/**
 * Art Deco Luxe — navy & gold frame, geometric fan ornaments, centered elegance.
 * Inspired by Gatsby / luxury hospitality CV designs.
 */
export function buildArtDecoLuxe(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const frame = 36;
  const innerW = A4_WIDTH - frame * 2;
  const gold = theme.accent;

  return [
    el({
      id: "bg",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: A4_HEIGHT,
      content: "",
      locked: true,
      style: { background: theme.background, borderRadius: 0 },
    }),
    el({
      id: "frame-outer",
      type: "section",
      x: frame - 4,
      y: frame - 4,
      width: innerW + 8,
      height: A4_HEIGHT - frame * 2 + 8,
      content: "",
      style: {
        background: "transparent",
        border: `2px solid ${gold}`,
      },
    }),
    el({
      id: "frame-inner",
      type: "section",
      x: frame + 8,
      y: frame + 8,
      width: innerW - 16,
      height: A4_HEIGHT - frame * 2 - 16,
      content: "",
      style: {
        border: `1px solid ${gold}60`,
      },
    }),
    el({
      id: "fan-left",
      type: "section",
      x: frame + 20,
      y: 80,
      width: 80,
      height: 120,
      content: "",
      style: {
        background: `linear-gradient(180deg, ${gold}30 0%, transparent 100%)`,
        borderRadius: 80,
        opacity: 0.6,
      },
    }),
    el({
      id: "fan-right",
      type: "section",
      x: A4_WIDTH - frame - 100,
      y: 80,
      width: 80,
      height: 120,
      content: "",
      style: {
        background: `linear-gradient(180deg, ${gold}30 0%, transparent 100%)`,
        borderRadius: 80,
        opacity: 0.6,
      },
    }),
    el({
      id: "top-ornament",
      type: "section",
      x: A4_WIDTH / 2 - 60,
      y: frame + 16,
      width: 120,
      height: 4,
      content: "",
      style: { background: gold, borderRadius: 0 },
    }),
    el({
      id: "diamond",
      type: "section",
      x: A4_WIDTH / 2 - 10,
      y: frame + 6,
      width: 20,
      height: 20,
      content: "",
      rotation: 45,
      style: { background: gold, borderRadius: 2 },
    }),
    el({
      id: "name",
      type: "text",
      x: frame + 40,
      y: 100,
      width: innerW - 80,
      height: 52,
      content: SAMPLE.name,
      style: {
        fontSize: 34,
        fontWeight: 400,
        color: gold,
        fontFamily: fonts.heading,
        textAlign: "center",
        letterSpacing: 4,
      },
    }),
    el({
      id: "title",
      type: "text",
      x: frame + 40,
      y: 158,
      width: innerW - 80,
      height: 24,
      content: SAMPLE.title.toUpperCase(),
      style: {
        fontSize: 11,
        color: theme.muted,
        fontFamily: fonts.body,
        textAlign: "center",
        letterSpacing: 6,
      },
    }),
    el({
      id: "divider-1",
      type: "section",
      x: A4_WIDTH / 2 - 100,
      y: 192,
      width: 200,
      height: 1,
      content: "",
      style: { background: `${gold}80`, borderRadius: 0 },
    }),
    el({
      id: "contact",
      type: "text",
      x: frame + 40,
      y: 204,
      width: innerW - 80,
      height: 18,
      content: SAMPLE.contact.replace(/\s•\s/g, "   ◆   "),
      style: {
        fontSize: 9,
        color: theme.muted,
        fontFamily: fonts.body,
        textAlign: "center",
        letterSpacing: 1,
      },
    }),
    el({
      id: "avatar",
      type: "image",
      x: A4_WIDTH / 2 - 50,
      y: 236,
      width: 100,
      height: 100,
      content: "",
      style: {
        background: `${gold}40`,
        borderRadius: 999,
        border: `2px solid ${gold}`,
      },
    }),
    el({
      id: "summary-panel",
      type: "section",
      x: frame + 32,
      y: 356,
      width: innerW - 64,
      height: 88,
      content: "",
      style: {
        background: `${gold}12`,
        border: `1px solid ${gold}40`,
        borderRadius: 0,
      },
    }),
    el({
      id: "summary-label",
      type: "text",
      x: frame + 48,
      y: 368,
      width: innerW - 96,
      height: 16,
      content: "— PROFESSIONAL SUMMARY —",
      style: {
        fontSize: 9,
        fontWeight: 700,
        color: gold,
        fontFamily: fonts.heading,
        textAlign: "center",
        letterSpacing: 3,
      },
    }),
    el({
      id: "summary",
      type: "text",
      x: frame + 48,
      y: 390,
      width: innerW - 96,
      height: 48,
      content: SAMPLE.summary,
      sectionType: "summary",
      style: {
        fontSize: 10,
        color: theme.text,
        fontFamily: fonts.body,
        textAlign: "center",
        lineHeight: 1.55,
        fontStyle: "italic",
      },
    }),
    el({
      id: "col-left-line",
      type: "section",
      x: frame + 32,
      y: 468,
      width: (innerW - 80) / 2,
      height: 2,
      content: "",
      style: { background: gold, borderRadius: 0 },
    }),
    el({
      id: "col-right-line",
      type: "section",
      x: frame + 48 + (innerW - 80) / 2,
      y: 468,
      width: (innerW - 80) / 2,
      height: 2,
      content: "",
      style: { background: gold, borderRadius: 0 },
    }),
    el({
      id: "experience-label",
      type: "text",
      x: frame + 32,
      y: 480,
      width: (innerW - 80) / 2,
      height: 18,
      content: "EXPERIENCE",
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: gold,
        fontFamily: fonts.heading,
        letterSpacing: 2,
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: frame + 32,
      y: 504,
      width: (innerW - 80) / 2 - 8,
      height: 200,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: {
        fontSize: 9,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.65,
      },
    }),
    el({
      id: "education-label",
      type: "text",
      x: frame + 48 + (innerW - 80) / 2,
      y: 480,
      width: (innerW - 80) / 2,
      height: 18,
      content: "EDUCATION",
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: gold,
        fontFamily: fonts.heading,
        letterSpacing: 2,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: frame + 48 + (innerW - 80) / 2,
      y: 504,
      width: (innerW - 80) / 2 - 8,
      height: 120,
      content: SAMPLE.education,
      sectionType: "education",
      style: {
        fontSize: 9,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.65,
      },
    }),
    el({
      id: "skills-label",
      type: "text",
      x: frame + 48 + (innerW - 80) / 2,
      y: 640,
      width: (innerW - 80) / 2,
      height: 18,
      content: "COMPETENCIES",
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: gold,
        fontFamily: fonts.heading,
        letterSpacing: 2,
      },
    }),
    el({
      id: "skills",
      type: "text",
      x: frame + 48 + (innerW - 80) / 2,
      y: 664,
      width: (innerW - 80) / 2 - 8,
      height: 100,
      content: SAMPLE.skills,
      sectionType: "skills",
      style: {
        fontSize: 9,
        color: theme.muted,
        fontFamily: fonts.body,
        lineHeight: 1.8,
      },
    }),
    el({
      id: "bottom-ornament",
      type: "section",
      x: A4_WIDTH / 2 - 80,
      y: A4_HEIGHT - frame - 28,
      width: 160,
      height: 4,
      content: "",
      style: { background: gold, borderRadius: 0 },
    }),
  ];
}
