import { A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Asymmetrical colorful blocks — designer portfolio feel */
export function buildCreativePortfolio(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  return [
    el({
      id: "hero-block",
      type: "section",
      x: 180,
      y: 32,
      width: A4_WIDTH - 212,
      height: 140,
      content: "",
      style: { background: theme.primary, borderRadius: 24 },
    }),
    el({
      id: "name",
      type: "text",
      x: 204,
      y: 56,
      width: 520,
      height: 44,
      content: SAMPLE.name,
      style: {
        fontSize: 28,
        fontWeight: 800,
        color: "#ffffff",
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "title",
      type: "text",
      x: 204,
      y: 104,
      width: 400,
      height: 28,
      content: SAMPLE.title,
      style: { fontSize: 14, color: theme.accent, fontFamily: fonts.body },
    }),
    el({
      id: "avatar",
      type: "image",
      x: 40,
      y: 72,
      width: 120,
      height: 120,
      content: "",
      style: {
        background: theme.accent,
        borderRadius: 20,
        boxShadow: "0 12px 32px rgba(0,0,0,0.2)",
      },
    }),
    el({
      id: "accent-block",
      type: "section",
      x: 40,
      y: 200,
      width: 120,
      height: 8,
      content: "",
      style: { background: theme.accent, borderRadius: 4 },
    }),
    el({
      id: "about-card",
      type: "section",
      x: 40,
      y: 228,
      width: 340,
      height: 120,
      content: "",
      style: { background: theme.surface ?? "#fef3c7", borderRadius: 16, padding: 16 },
    }),
    el({
      id: "summary",
      type: "text",
      x: 56,
      y: 244,
      width: 308,
      height: 88,
      content: SAMPLE.summary,
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "skills-card",
      type: "section",
      x: 404,
      y: 228,
      width: 350,
      height: 120,
      content: "",
      style: { background: theme.primary, borderRadius: 16, opacity: 0.12 },
    }),
    el({
      id: "skills",
      type: "text",
      x: 420,
      y: 248,
      width: 318,
      height: 80,
      content: SAMPLE.skills,
      sectionType: "skills",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.7 },
    }),
    el({
      id: "exp-label",
      type: "text",
      x: 40,
      y: 372,
      width: 200,
      height: 32,
      content: "Work",
      style: {
        fontSize: 22,
        fontWeight: 800,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "exp-block",
      type: "section",
      x: 40,
      y: 412,
      width: A4_WIDTH - 80,
      height: 200,
      content: "",
      style: {
        background: "#ffffff",
        border: `3px solid ${theme.primary}`,
        borderRadius: 0,
        padding: 20,
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: 60,
      y: 432,
      width: A4_WIDTH - 120,
      height: 160,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "edu-chip",
      type: "section",
      x: 40,
      y: 640,
      width: 280,
      height: 100,
      content: "",
      style: { background: theme.accent, borderRadius: 12, opacity: 0.2 },
    }),
    el({
      id: "education",
      type: "text",
      x: 56,
      y: 656,
      width: 248,
      height: 72,
      content: SAMPLE.education,
      sectionType: "education",
      style: { fontSize: 10, color: theme.text, fontFamily: fonts.body, lineHeight: 1.5 },
    }),
  ];
}
