import { A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Hard edges, massive type, brutalist UI */
export function buildBrutalistBold(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const pad = 32;

  return [
    el({
      id: "frame",
      type: "section",
      x: pad,
      y: pad,
      width: A4_WIDTH - pad * 2,
      height: 1040,
      content: "",
      style: { border: `6px solid ${theme.text}`, borderRadius: 0, background: theme.background },
    }),
    el({
      id: "name",
      type: "text",
      x: pad + 24,
      y: pad + 24,
      width: A4_WIDTH - pad * 2 - 48,
      height: 72,
      content: SAMPLE.name.toUpperCase(),
      style: {
        fontSize: 48,
        fontWeight: 900,
        color: theme.text,
        fontFamily: fonts.heading,
        lineHeight: 0.95,
        letterSpacing: -2,
      },
    }),
    el({
      id: "title-bar",
      type: "section",
      x: pad + 24,
      y: pad + 108,
      width: 320,
      height: 36,
      content: "",
      style: { background: theme.text, borderRadius: 0 },
    }),
    el({
      id: "title",
      type: "text",
      x: pad + 36,
      y: pad + 116,
      width: 296,
      height: 24,
      content: SAMPLE.title.toUpperCase(),
      style: {
        fontSize: 13,
        fontWeight: 700,
        color: theme.background,
        fontFamily: fonts.body,
        letterSpacing: 2,
      },
    }),
    el({
      id: "contact",
      type: "text",
      x: pad + 24,
      y: pad + 160,
      width: A4_WIDTH - pad * 2 - 48,
      height: 20,
      content: SAMPLE.contact.toUpperCase(),
      style: {
        fontSize: 9,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.body,
        letterSpacing: 1,
      },
    }),
    el({
      id: "divider",
      type: "section",
      x: pad + 24,
      y: pad + 196,
      width: A4_WIDTH - pad * 2 - 48,
      height: 4,
      content: "",
      style: { background: theme.accent, borderRadius: 0 },
    }),
    el({
      id: "summary-label",
      type: "text",
      x: pad + 24,
      y: pad + 220,
      width: 200,
      height: 28,
      content: "01 / ABOUT",
      style: {
        fontSize: 16,
        fontWeight: 900,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "summary",
      type: "text",
      x: pad + 24,
      y: pad + 256,
      width: A4_WIDTH - pad * 2 - 48,
      height: 64,
      content: SAMPLE.summary,
      style: { fontSize: 12, color: theme.text, fontFamily: fonts.body, lineHeight: 1.5 },
    }),
    el({
      id: "exp-label",
      type: "text",
      x: pad + 24,
      y: pad + 340,
      width: 240,
      height: 28,
      content: "02 / EXPERIENCE",
      style: {
        fontSize: 16,
        fontWeight: 900,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "exp-box",
      type: "section",
      x: pad + 24,
      y: pad + 376,
      width: A4_WIDTH - pad * 2 - 48,
      height: 220,
      content: "",
      style: { border: `3px solid ${theme.text}`, borderRadius: 0, padding: 16 },
    }),
    el({
      id: "experience",
      type: "text",
      x: pad + 40,
      y: pad + 392,
      width: A4_WIDTH - pad * 2 - 80,
      height: 188,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.55 },
    }),
    el({
      id: "skills-label",
      type: "text",
      x: pad + 24,
      y: pad + 620,
      width: 200,
      height: 28,
      content: "03 / SKILLS",
      style: {
        fontSize: 16,
        fontWeight: 900,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "skills",
      type: "text",
      x: pad + 24,
      y: pad + 656,
      width: A4_WIDTH - pad * 2 - 48,
      height: 80,
      content: SAMPLE.skills.toUpperCase().replace(/\n/g, "  •  "),
      sectionType: "skills",
      style: {
        fontSize: 11,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.8,
      },
    }),
  ];
}
