import { A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Black luxury with gold accents — executive serif typography */
export function buildExecutiveDark(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const pad = 64;
  const w = A4_WIDTH - pad * 2;

  return [
    el({
      id: "top-bar",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: 6,
      content: "",
      style: { background: theme.accent },
    }),
    el({
      id: "name",
      type: "text",
      x: pad,
      y: 72,
      width: w,
      height: 52,
      content: SAMPLE.name.toUpperCase(),
      style: {
        fontSize: 34,
        fontWeight: 400,
        color: "#ffffff",
        fontFamily: fonts.heading,
        letterSpacing: 6,
        textAlign: "center",
      },
    }),
    el({
      id: "title",
      type: "text",
      x: pad,
      y: 132,
      width: w,
      height: 24,
      content: SAMPLE.title,
      style: {
        fontSize: 13,
        color: theme.accent,
        fontFamily: fonts.body,
        textAlign: "center",
        letterSpacing: 3,
      },
    }),
    el({
      id: "gold-rule",
      type: "section",
      x: A4_WIDTH / 2 - 80,
      y: 172,
      width: 160,
      height: 1,
      content: "",
      style: { background: theme.accent, opacity: 0.8 },
    }),
    el({
      id: "contact",
      type: "text",
      x: pad,
      y: 188,
      width: w,
      height: 20,
      content: SAMPLE.contact.replace(/•/g, "|"),
      style: {
        fontSize: 10,
        color: theme.muted,
        fontFamily: fonts.body,
        textAlign: "center",
        letterSpacing: 1,
      },
    }),
    el({
      id: "summary-card",
      type: "section",
      x: pad,
      y: 240,
      width: w,
      height: 88,
      content: "",
      style: {
        background: "rgba(201,169,98,0.08)",
        border: `1px solid ${theme.accent}40`,
        borderRadius: 0,
        padding: 20,
      },
    }),
    el({
      id: "summary",
      type: "text",
      x: pad + 20,
      y: 256,
      width: w - 40,
      height: 56,
      content: SAMPLE.summary,
      style: {
        fontSize: 11,
        color: "#e4e4e7",
        fontFamily: fonts.body,
        lineHeight: 1.7,
        textAlign: "center",
        fontStyle: "italic",
      },
    }),
    el({
      id: "exp-label",
      type: "text",
      x: pad,
      y: 352,
      width: w,
      height: 22,
      content: "PROFESSIONAL EXPERIENCE",
      style: {
        fontSize: 10,
        fontWeight: 700,
        letterSpacing: 4,
        color: theme.accent,
        fontFamily: fonts.heading,
        textAlign: "center",
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: pad + 40,
      y: 384,
      width: w - 80,
      height: 180,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: { fontSize: 11, color: "#fafafa", fontFamily: fonts.body, lineHeight: 1.65 },
    }),
    el({
      id: "edu-label",
      type: "text",
      x: pad,
      y: 580,
      width: w,
      height: 22,
      content: "EDUCATION",
      style: {
        fontSize: 10,
        fontWeight: 700,
        letterSpacing: 4,
        color: theme.accent,
        fontFamily: fonts.heading,
        textAlign: "center",
      },
    }),
    el({
      id: "education",
      type: "text",
      x: pad + 40,
      y: 612,
      width: w - 80,
      height: 72,
      content: SAMPLE.education,
      sectionType: "education",
      style: {
        fontSize: 11,
        color: theme.muted,
        fontFamily: fonts.body,
        lineHeight: 1.55,
        textAlign: "center",
      },
    }),
  ];
}
