import type { TemplateSlug } from "@/templates/registry";

export interface TemplateCatalogEntry {
  id: string;
  slug: TemplateSlug;
  name: string;
  category: string;
  description: string;
  previewImage: string;
  fontFamily: string;
  atsOptimized: boolean;
  premium: boolean;
  layout: string;
}

/** Real static preview paths — generated by scripts/generate-template-previews.mjs */
export const TEMPLATE_PREVIEW_BASE = "/templates";

export function getTemplatePreviewPath(slug: string): string {
  return `${TEMPLATE_PREVIEW_BASE}/${slug}.svg`;
}

export const TEMPLATE_CATALOG: TemplateCatalogEntry[] = [
  {
    id: "tpl-minimal-corporate",
    slug: "minimal-corporate",
    name: "Minimal Corporate",
    category: "Professional",
    description: "Clean ATS-safe layout with thin typography and recruiter-friendly structure.",
    previewImage: getTemplatePreviewPath("minimal-corporate"),
    fontFamily: "Inter",
    atsOptimized: true,
    premium: false,
    layout: "single-column",
  },
  {
    id: "tpl-modern-split",
    slug: "modern-split",
    name: "Modern Split",
    category: "Modern",
    description: "Left sidebar with avatar, skills bars, and modern two-column flow.",
    previewImage: getTemplatePreviewPath("modern-split"),
    fontFamily: "Inter",
    atsOptimized: true,
    premium: false,
    layout: "sidebar",
  },
  {
    id: "tpl-executive-dark",
    slug: "executive-dark",
    name: "Executive Dark",
    category: "Executive",
    description: "Luxury dark theme with gold accents and serif executive typography.",
    previewImage: getTemplatePreviewPath("executive-dark"),
    fontFamily: "Playfair Display",
    atsOptimized: false,
    premium: true,
    layout: "sidebar",
  },
  {
    id: "tpl-creative-portfolio",
    slug: "creative-portfolio",
    name: "Creative Portfolio",
    category: "Creative",
    description: "Magazine-style blocks, bold color panels, and portfolio-first hierarchy.",
    previewImage: getTemplatePreviewPath("creative-portfolio"),
    fontFamily: "Poppins",
    atsOptimized: false,
    premium: true,
    layout: "card-grid",
  },
  {
    id: "tpl-brutalist-bold",
    slug: "brutalist-bold",
    name: "Brutalist Bold",
    category: "Creative",
    description: "Hard edges, massive type, and high-contrast experimental layout.",
    previewImage: getTemplatePreviewPath("brutalist-bold"),
    fontFamily: "Space Grotesk",
    atsOptimized: false,
    premium: true,
    layout: "single-column",
  },
  {
    id: "tpl-timeline-resume",
    slug: "timeline-resume",
    name: "Timeline Resume",
    category: "Modern",
    description: "Vertical timeline with connected experience nodes and date column.",
    previewImage: getTemplatePreviewPath("timeline-resume"),
    fontFamily: "Inter",
    atsOptimized: true,
    premium: false,
    layout: "timeline",
  },
  {
    id: "tpl-apple-minimal",
    slug: "apple-minimal",
    name: "Apple Minimal",
    category: "Modern",
    description: "Ultra whitespace, centered hierarchy, and SF-inspired minimal type.",
    previewImage: getTemplatePreviewPath("apple-minimal"),
    fontFamily: "Inter",
    atsOptimized: true,
    premium: true,
    layout: "single-column",
  },
  {
    id: "tpl-neon-cyber",
    slug: "neon-cyber",
    name: "Neon Cyber",
    category: "Creative",
    description: "Cyberpunk gradients, glowing borders, and neon monospace accents.",
    previewImage: getTemplatePreviewPath("neon-cyber"),
    fontFamily: "Space Grotesk",
    atsOptimized: false,
    premium: true,
    layout: "two-column",
  },
  {
    id: "tpl-glassmorphism",
    slug: "glassmorphism",
    name: "Neo Glass",
    category: "Modern",
    description: "Floating glass cards on mesh gradient — modern UI portfolio feel.",
    previewImage: getTemplatePreviewPath("glassmorphism"),
    fontFamily: "DM Sans",
    atsOptimized: false,
    premium: true,
    layout: "card-grid",
  },
  {
    id: "tpl-magazine-editorial",
    slug: "magazine-editorial",
    name: "Magazine CV",
    category: "Creative",
    description: "Editorial serif headlines with newspaper-style two-column grid.",
    previewImage: getTemplatePreviewPath("magazine-editorial"),
    fontFamily: "Lora",
    atsOptimized: false,
    premium: true,
    layout: "two-column",
  },
  {
    id: "tpl-canva-creative",
    slug: "canva-creative",
    name: "Corporate Blue",
    category: "Creative",
    description: "Infographic skill pills, colorful header band, Canva-style blocks.",
    previewImage: getTemplatePreviewPath("canva-creative"),
    fontFamily: "Poppins",
    atsOptimized: false,
    premium: true,
    layout: "card-grid",
  },
  {
    id: "tpl-ats-ultra",
    slug: "ats-ultra-professional",
    name: "Minimal ATS",
    category: "Professional",
    description: "Plain-text maximum ATS parsing with zero decorative noise.",
    previewImage: getTemplatePreviewPath("ats-ultra-professional"),
    fontFamily: "IBM Plex Sans",
    atsOptimized: true,
    premium: false,
    layout: "single-column",
  },
];

export function getCatalogEntry(slugOrId: string): TemplateCatalogEntry | undefined {
  return TEMPLATE_CATALOG.find((t) => t.slug === slugOrId || t.id === slugOrId);
}

export function resolveTemplateSlug(slugOrId: string | null): string | null {
  if (!slugOrId) return null;
  const entry = getCatalogEntry(slugOrId);
  if (entry) return entry.slug;
  return slugOrId;
}
