import type { ColorPalette, DesignTheme, FontPairing } from "@/types/design-system";

export const FONT_PAIRINGS: FontPairing[] = [
  { id: "inter-system", heading: "Inter", body: "Inter", label: "Modern SaaS" },
  { id: "georgia-serif", heading: "Georgia", body: "Inter", label: "Executive Classic" },
  { id: "mono-tech", heading: "JetBrains Mono", body: "Inter", label: "Tech / FAANG" },
  { id: "playfair-luxury", heading: "Playfair Display", body: "Inter", label: "Luxury" },
];

export const PALETTES: ColorPalette[] = [
  {
    id: "zinc-pro",
    name: "Professional Zinc",
    primary: "#18181b",
    secondary: "#52525b",
    accent: "#3b82f6",
    background: "#ffffff",
    surface: "#fafafa",
    text: "#18181b",
    textMuted: "#71717a",
    tags: ["corporate", "ats", "minimal"],
  },
  {
    id: "startup-indigo",
    name: "Startup Indigo",
    primary: "#312e81",
    secondary: "#6366f1",
    accent: "#818cf8",
    background: "#ffffff",
    surface: "#f5f3ff",
    text: "#1e1b4b",
    textMuted: "#64748b",
    gradient: "linear-gradient(135deg, #6366f1 0%, #818cf8 100%)",
    tags: ["startup", "modern"],
  },
  {
    id: "luxury-gold",
    name: "Luxury Black Gold",
    primary: "#0a0a0a",
    secondary: "#1c1917",
    accent: "#d4af37",
    background: "#0a0a0a",
    surface: "#171717",
    text: "#fafafa",
    textMuted: "#a3a3a3",
    gradient: "linear-gradient(135deg, #d4af37 0%, #f5e6a3 50%, #d4af37 100%)",
    tags: ["luxury", "dark", "executive"],
  },
  {
    id: "cyber-neon",
    name: "Cyber Neon",
    primary: "#0f172a",
    secondary: "#1e293b",
    accent: "#22d3ee",
    background: "#020617",
    surface: "#0f172a",
    text: "#e2e8f0",
    textMuted: "#94a3b8",
    gradient: "linear-gradient(135deg, #22d3ee 0%, #a855f7 100%)",
    tags: ["cyber", "futuristic", "creative"],
  },
  {
    id: "glass-light",
    name: "Glass Light",
    primary: "#18181b",
    secondary: "#71717a",
    accent: "#6366f1",
    background: "rgba(255,255,255,0.72)",
    surface: "rgba(255,255,255,0.5)",
    text: "#18181b",
    textMuted: "#52525b",
    tags: ["glass", "glassmorphism", "modern"],
  },
  {
    id: "faang-clean",
    name: "FAANG Clean",
    primary: "#111827",
    secondary: "#374151",
    accent: "#059669",
    background: "#ffffff",
    surface: "#f9fafb",
    text: "#111827",
    textMuted: "#6b7280",
    tags: ["faang", "ats", "recruiter"],
  },
];

const baseEffects = {
  glow: false,
  blur: 0,
  shadowDepth: "soft" as const,
  borderRadius: 12,
  glassOpacity: 0,
  animatedGradient: false,
};

export const DESIGN_THEMES: DesignTheme[] = [
  {
    id: "minimal-corporate",
    name: "Minimal Corporate",
    aesthetic: "minimal",
    mode: "light",
    palette: PALETTES[0]!,
    fonts: FONT_PAIRINGS[0]!,
    spacing: 16,
    density: "balanced",
    animation: "none",
    effects: baseEffects,
    atsScore: 96,
    recruiterScore: 94,
    modernity: 78,
    creativity: 35,
    minimalism: 92,
  },
  {
    id: "startup-bold",
    name: "Startup Bold",
    aesthetic: "startup",
    mode: "light",
    palette: PALETTES[1]!,
    fonts: FONT_PAIRINGS[0]!,
    spacing: 20,
    density: "spacious",
    animation: "subtle",
    effects: { ...baseEffects, shadowDepth: "medium" },
    atsScore: 88,
    recruiterScore: 86,
    modernity: 92,
    creativity: 72,
    minimalism: 55,
  },
  {
    id: "luxury-executive",
    name: "Luxury Executive",
    aesthetic: "luxury",
    mode: "dark",
    palette: PALETTES[2]!,
    fonts: FONT_PAIRINGS[3]!,
    spacing: 24,
    density: "spacious",
    animation: "subtle",
    effects: { ...baseEffects, glow: true, shadowDepth: "lift" },
    atsScore: 82,
    recruiterScore: 90,
    modernity: 85,
    creativity: 68,
    minimalism: 70,
  },
  {
    id: "cyber-future",
    name: "Cyber Future",
    aesthetic: "cyber",
    mode: "dark",
    palette: PALETTES[3]!,
    fonts: FONT_PAIRINGS[2]!,
    spacing: 18,
    density: "balanced",
    animation: "cinematic",
    effects: { ...baseEffects, glow: true, animatedGradient: true, blur: 8 },
    atsScore: 72,
    recruiterScore: 75,
    modernity: 98,
    creativity: 95,
    minimalism: 40,
  },
  {
    id: "glass-modern",
    name: "Glass Modern",
    aesthetic: "glass",
    mode: "light",
    palette: PALETTES[4]!,
    fonts: FONT_PAIRINGS[0]!,
    spacing: 16,
    density: "balanced",
    animation: "moderate",
    effects: { ...baseEffects, blur: 12, glassOpacity: 0.65, borderRadius: 16 },
    atsScore: 85,
    recruiterScore: 82,
    modernity: 94,
    creativity: 80,
    minimalism: 65,
  },
  {
    id: "faang-ats",
    name: "FAANG ATS",
    aesthetic: "faang",
    mode: "light",
    palette: PALETTES[5]!,
    fonts: FONT_PAIRINGS[2]!,
    spacing: 14,
    density: "compact",
    animation: "none",
    effects: baseEffects,
    atsScore: 98,
    recruiterScore: 97,
    modernity: 80,
    creativity: 30,
    minimalism: 88,
  },
  {
    id: "brutalist-bold",
    name: "Brutalist Bold",
    aesthetic: "brutalist",
    mode: "light",
    palette: { ...PALETTES[0]!, accent: "#dc2626" },
    fonts: FONT_PAIRINGS[0]!,
    spacing: 12,
    density: "compact",
    animation: "none",
    effects: { ...baseEffects, borderRadius: 0, shadowDepth: "none" },
    atsScore: 75,
    recruiterScore: 70,
    modernity: 88,
    creativity: 90,
    minimalism: 45,
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    aesthetic: "portfolio",
    mode: "light",
    palette: PALETTES[1]!,
    fonts: FONT_PAIRINGS[3]!,
    spacing: 22,
    density: "spacious",
    animation: "moderate",
    effects: { ...baseEffects, shadowDepth: "lift" },
    atsScore: 70,
    recruiterScore: 78,
    modernity: 90,
    creativity: 98,
    minimalism: 50,
  },
];

export function getThemeById(id: string): DesignTheme | undefined {
  return DESIGN_THEMES.find((t) => t.id === id);
}
