import { A4_HEIGHT, A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/**
 * Swiss International — poster grid, red spine, yellow accent block, bold typography.
 * Inspired by Swiss / Bauhaus editorial CV designs.
 */
export function buildSwissInternational(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const spineW = 28;
  const pad = 56;
  const contentX = spineW + pad;
  const contentW = A4_WIDTH - contentX - pad;

  return [
    el({
      id: "spine",
      type: "section",
      x: 0,
      y: 0,
      width: spineW,
      height: A4_HEIGHT,
      content: "",
      locked: true,
      style: { background: theme.primary, borderRadius: 0 },
    }),
    el({
      id: "accent-square",
      type: "section",
      x: A4_WIDTH - 120,
      y: 48,
      width: 72,
      height: 72,
      content: "",
      style: { background: theme.accent, borderRadius: 0 },
    }),
    el({
      id: "accent-square-2",
      type: "section",
      x: A4_WIDTH - 168,
      y: 132,
      width: 40,
      height: 40,
      content: "",
      style: { background: theme.text, borderRadius: 0, opacity: 0.08 },
    }),
    el({
      id: "name",
      type: "text",
      x: contentX,
      y: 48,
      width: contentW - 100,
      height: 72,
      content: SAMPLE.name.toUpperCase(),
      style: {
        fontSize: 42,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.heading,
        lineHeight: 0.95,
        letterSpacing: -1,
      },
    }),
    el({
      id: "title-bar",
      type: "section",
      x: contentX,
      y: 128,
      width: 180,
      height: 28,
      content: "",
      style: { background: theme.text, borderRadius: 0 },
    }),
    el({
      id: "title",
      type: "text",
      x: contentX + 12,
      y: 134,
      width: 156,
      height: 18,
      content: SAMPLE.title.toUpperCase(),
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: "#ffffff",
        fontFamily: fonts.body,
        letterSpacing: 1.5,
      },
    }),
    el({
      id: "contact",
      type: "text",
      x: contentX,
      y: 172,
      width: contentW,
      height: 20,
      content: SAMPLE.contact,
      style: {
        fontSize: 9,
        color: theme.muted,
        fontFamily: fonts.body,
        letterSpacing: 0.5,
      },
    }),
    el({
      id: "grid-line-1",
      type: "section",
      x: contentX,
      y: 208,
      width: contentW,
      height: 3,
      content: "",
      style: { background: theme.text, borderRadius: 0 },
    }),
    el({
      id: "summary-num",
      type: "text",
      x: contentX,
      y: 228,
      width: 48,
      height: 48,
      content: "01",
      style: {
        fontSize: 36,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
        lineHeight: 1,
      },
    }),
    el({
      id: "summary-label",
      type: "text",
      x: contentX + 56,
      y: 236,
      width: 200,
      height: 20,
      content: "PROFILE",
      style: {
        fontSize: 11,
        fontWeight: 700,
        letterSpacing: 3,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "summary",
      type: "text",
      x: contentX + 56,
      y: 260,
      width: contentW - 56,
      height: 64,
      content: SAMPLE.summary,
      sectionType: "summary",
      style: {
        fontSize: 10,
        color: theme.muted,
        fontFamily: fonts.body,
        lineHeight: 1.5,
      },
    }),
    el({
      id: "grid-line-2",
      type: "section",
      x: contentX,
      y: 340,
      width: contentW,
      height: 1,
      content: "",
      style: { background: theme.muted, opacity: 0.35, borderRadius: 0 },
    }),
    el({
      id: "exp-num",
      type: "text",
      x: contentX,
      y: 356,
      width: 48,
      height: 48,
      content: "02",
      style: {
        fontSize: 36,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
        lineHeight: 1,
      },
    }),
    el({
      id: "experience-label",
      type: "text",
      x: contentX + 56,
      y: 364,
      width: 200,
      height: 20,
      content: "EXPERIENCE",
      style: {
        fontSize: 11,
        fontWeight: 700,
        letterSpacing: 3,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: contentX + 56,
      y: 388,
      width: contentW - 56,
      height: 180,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: {
        fontSize: 10,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.6,
      },
    }),
    el({
      id: "bottom-band",
      type: "section",
      x: spineW,
      y: A4_HEIGHT - 140,
      width: A4_WIDTH - spineW,
      height: 140,
      content: "",
      style: { background: theme.surface ?? "#f5f5f4", borderRadius: 0 },
    }),
    el({
      id: "edu-num",
      type: "text",
      x: contentX,
      y: A4_HEIGHT - 120,
      width: 48,
      height: 40,
      content: "03",
      style: {
        fontSize: 28,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: contentX + 56,
      y: A4_HEIGHT - 116,
      width: (contentW - 56) / 2,
      height: 90,
      content: SAMPLE.education,
      sectionType: "education",
      style: {
        fontSize: 10,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.55,
      },
    }),
    el({
      id: "skills-block",
      type: "section",
      x: contentX + contentW / 2 + 20,
      y: A4_HEIGHT - 108,
      width: contentW / 2 - 36,
      height: 72,
      content: "",
      style: {
        background: theme.accent,
        borderRadius: 0,
        padding: 12,
      },
    }),
    el({
      id: "skills",
      type: "text",
      x: contentX + contentW / 2 + 32,
      y: A4_HEIGHT - 96,
      width: contentW / 2 - 56,
      height: 56,
      content: SAMPLE.skills.replace(/\n/g, "  ·  "),
      sectionType: "skills",
      style: {
        fontSize: 9,
        fontWeight: 600,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.8,
      },
    }),
  ];
}
