import { A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Canva-style infographic — colorful blocks, visual hierarchy */
export function buildCanvaCreative(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const colors = [theme.primary, theme.accent, "#f472b6", "#34d399", "#fbbf24"];

  return [
    el({
      id: "header-strip",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: 120,
      content: "",
      style: { background: theme.primary, borderRadius: 0 },
    }),
    el({
      id: "strip-accent",
      type: "section",
      x: 0,
      y: 120,
      width: A4_WIDTH,
      height: 8,
      content: "",
      style: { background: theme.accent },
    }),
    el({
      id: "name",
      type: "text",
      x: 48,
      y: 36,
      width: 480,
      height: 40,
      content: SAMPLE.name,
      style: {
        fontSize: 28,
        fontWeight: 800,
        color: "#ffffff",
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "title",
      type: "text",
      x: 48,
      y: 78,
      width: 400,
      height: 24,
      content: SAMPLE.title,
      style: { fontSize: 13, color: "rgba(255,255,255,0.9)", fontFamily: fonts.body },
    }),
    el({
      id: "avatar",
      type: "image",
      x: 620,
      y: 24,
      width: 96,
      height: 96,
      content: "",
      style: {
        background: "#ffffff",
        borderRadius: 999,
        border: `4px solid ${theme.accent}`,
      },
    }),
    el({
      id: "block-1",
      type: "section",
      x: 48,
      y: 152,
      width: 220,
      height: 100,
      content: "",
      style: { background: colors[2], borderRadius: 12, opacity: 0.85 },
    }),
    el({
      id: "summary",
      type: "text",
      x: 60,
      y: 168,
      width: 196,
      height: 72,
      content: SAMPLE.summary.slice(0, 100) + "…",
      style: { fontSize: 9, color: "#ffffff", fontFamily: fonts.body, lineHeight: 1.5 },
    }),
    el({
      id: "block-2",
      type: "section",
      x: 284,
      y: 152,
      width: 220,
      height: 100,
      content: "",
      style: { background: colors[3], borderRadius: 12, opacity: 0.85 },
    }),
    el({
      id: "contact",
      type: "text",
      x: 296,
      y: 172,
      width: 196,
      height: 64,
      content: SAMPLE.contact.replace(/•/g, "\n"),
      style: { fontSize: 9, color: "#ffffff", fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "block-3",
      type: "section",
      x: 520,
      y: 152,
      width: 226,
      height: 100,
      content: "",
      style: { background: colors[4], borderRadius: 12, opacity: 0.85 },
    }),
    el({
      id: "languages",
      type: "text",
      x: 532,
      y: 172,
      width: 202,
      height: 64,
      content: SAMPLE.languages,
      style: { fontSize: 9, color: theme.text, fontFamily: fonts.body, lineHeight: 1.5 },
    }),
    el({
      id: "skills-label",
      type: "text",
      x: 48,
      y: 276,
      width: 200,
      height: 22,
      content: "Skills",
      style: {
        fontSize: 16,
        fontWeight: 800,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    ...SAMPLE.skills.split("\n").slice(0, 5).map((skill, i) =>
      el({
        id: `skill-bar-${i}`,
        type: "section",
        x: 48,
        y: 308 + i * 36,
        width: 120 + i * 40,
        height: 24,
        content: "",
        style: {
          background: colors[i % colors.length],
          borderRadius: 6,
          opacity: 0.75,
        },
      })
    ),
    ...SAMPLE.skills.split("\n").slice(0, 5).map((skill, i) =>
      el({
        id: `skill-label-${i}`,
        type: "text",
        x: 60,
        y: 312 + i * 36,
        width: 200,
        height: 18,
        content: skill,
        style: { fontSize: 10, fontWeight: 600, color: "#ffffff", fontFamily: fonts.body },
      })
    ),
    el({
      id: "exp-label",
      type: "text",
      x: 48,
      y: 500,
      width: 200,
      height: 22,
      content: "Experience",
      style: {
        fontSize: 16,
        fontWeight: 800,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "exp-card",
      type: "section",
      x: 48,
      y: 532,
      width: A4_WIDTH - 96,
      height: 200,
      content: "",
      style: {
        background: theme.surface ?? "#f8fafc",
        borderRadius: 16,
        border: `2px solid ${theme.primary}20`,
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: 64,
      y: 548,
      width: A4_WIDTH - 128,
      height: 168,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "edu-block",
      type: "section",
      x: 48,
      y: 752,
      width: 340,
      height: 88,
      content: "",
      style: { background: theme.primary, borderRadius: 12, opacity: 0.15 },
    }),
    el({
      id: "education",
      type: "text",
      x: 64,
      y: 768,
      width: 308,
      height: 56,
      content: SAMPLE.education,
      sectionType: "education",
      style: { fontSize: 10, color: theme.text, fontFamily: fonts.body, lineHeight: 1.5 },
    }),
  ];
}
