import type { CoreTemplateCategory } from "@/lib/design-engine/core-templates";
import type { CvEditorTemplate } from "@/types/cv-editor";
import type { DesignTheme, TemplateMetadata } from "@/types/design-system";
import type { TemplateSlug } from "@/templates/registry";
import { getCatalogEntry, getTemplatePreviewPath } from "@/templates/data/catalog";

const baseEffects = {
  glow: false,
  blur: 0,
  shadowDepth: "soft" as const,
  borderRadius: 8,
  glassOpacity: 0,
  animatedGradient: false,
};

function theme(
  id: string,
  name: string,
  aesthetic: DesignTheme["aesthetic"],
  palette: DesignTheme["palette"],
  fonts: DesignTheme["fonts"],
  opts: Partial<DesignTheme> = {}
): DesignTheme {
  return {
    id,
    name,
    aesthetic,
    mode: opts.mode ?? "light",
    palette,
    fonts,
    spacing: opts.spacing ?? 16,
    density: opts.density ?? "balanced",
    animation: opts.animation ?? "none",
    effects: opts.effects ?? baseEffects,
    atsScore: opts.atsScore ?? 85,
    recruiterScore: opts.recruiterScore ?? 88,
    modernity: opts.modernity ?? 80,
    creativity: opts.creativity ?? 50,
    minimalism: opts.minimalism ?? 70,
  };
}

export interface DistinctTemplateDef {
  slug: TemplateSlug;
  id: string;
  name: string;
  category: CoreTemplateCategory;
  premium: boolean;
  atsOptimized: boolean;
  layout: TemplateMetadata["layout"];
  designLanguage: string;
  industry: string[];
  colors: CvEditorTemplate["colors"];
  fonts: CvEditorTemplate["fonts"];
  designTheme: DesignTheme;
}

export const DISTINCT_TEMPLATES: DistinctTemplateDef[] = [
  {
    slug: "minimal-corporate",
    id: "tpl-minimal-corporate",
    name: "Minimal Corporate",
    category: "Professional",
    premium: false,
    atsOptimized: true,
    layout: "single-column",
    designLanguage: "Ultra-clean ATS recruiter layout",
    industry: ["Finance", "Consulting", "Corporate"],
    colors: {
      primary: "#18181b",
      accent: "#52525b",
      background: "#ffffff",
      text: "#27272a",
      muted: "#71717a",
    },
    fonts: { heading: "Inter", body: "Inter" },
    designTheme: theme(
      "minimal-corporate",
      "Minimal Corporate",
      "minimal",
      {
        id: "mc-palette",
        name: "Corporate",
        primary: "#18181b",
        secondary: "#52525b",
        accent: "#52525b",
        background: "#ffffff",
        surface: "#fafafa",
        text: "#27272a",
        textMuted: "#71717a",
        tags: ["clean"],
      },
      { id: "inter", heading: "Inter", body: "Inter", label: "Inter" },
      { atsScore: 98, minimalism: 95, creativity: 20 }
    ),
  },
  {
    slug: "modern-split",
    id: "tpl-modern-split",
    name: "Modern Split",
    category: "Modern",
    premium: false,
    atsOptimized: true,
    layout: "sidebar",
    designLanguage: "Left sidebar two-column with avatar",
    industry: ["Technology", "Product", "SaaS"],
    colors: {
      primary: "#1e3a5f",
      accent: "#38bdf8",
      background: "#ffffff",
      text: "#1e293b",
      muted: "#64748b",
    },
    fonts: { heading: "Inter", body: "Inter" },
    designTheme: theme(
      "modern-split",
      "Modern Split",
      "startup",
      {
        id: "ms-palette",
        name: "Ocean",
        primary: "#1e3a5f",
        secondary: "#0ea5e9",
        accent: "#38bdf8",
        background: "#ffffff",
        surface: "#f0f9ff",
        text: "#1e293b",
        textMuted: "#64748b",
        tags: ["modern"],
      },
      { id: "inter", heading: "Inter", body: "Inter", label: "Inter" },
      { atsScore: 90, modernity: 92 }
    ),
  },
  {
    slug: "executive-dark",
    id: "tpl-executive-dark",
    name: "Executive Dark",
    category: "Executive",
    premium: true,
    atsOptimized: false,
    layout: "sidebar",
    designLanguage: "Luxury dark with gold accents",
    industry: ["Executive", "Leadership", "C-Suite"],
    colors: {
      primary: "#c9a962",
      accent: "#c9a962",
      background: "#0a0a0a",
      text: "#fafafa",
      muted: "#a1a1aa",
    },
    fonts: { heading: "Georgia", body: "Georgia" },
    designTheme: theme(
      "executive-dark",
      "Executive Dark",
      "luxury",
      {
        id: "ed-palette",
        name: "Gold Black",
        primary: "#c9a962",
        secondary: "#1a1a1a",
        accent: "#c9a962",
        background: "#0a0a0a",
        surface: "#141414",
        text: "#fafafa",
        textMuted: "#a1a1aa",
        tags: ["luxury"],
      },
      { id: "georgia", heading: "Georgia", body: "Georgia", label: "Georgia" },
      { mode: "dark", atsScore: 72, creativity: 75, effects: { ...baseEffects, glow: true } }
    ),
  },
  {
    slug: "creative-portfolio",
    id: "tpl-creative-portfolio",
    name: "Creative Portfolio",
    category: "Creative",
    premium: true,
    atsOptimized: false,
    layout: "card-grid",
    designLanguage: "Asymmetrical colorful designer blocks",
    industry: ["Design", "Creative", "Freelance"],
    colors: {
      primary: "#7c3aed",
      accent: "#f59e0b",
      background: "#faf5ff",
      text: "#1e1b4b",
      muted: "#6b7280",
    },
    fonts: { heading: "Inter", body: "Inter" },
    designTheme: theme(
      "creative-portfolio",
      "Creative Portfolio",
      "portfolio",
      {
        id: "cp-palette",
        name: "Violet",
        primary: "#7c3aed",
        secondary: "#f59e0b",
        accent: "#f59e0b",
        background: "#faf5ff",
        surface: "#fef3c7",
        text: "#1e1b4b",
        textMuted: "#6b7280",
        tags: ["creative"],
      },
      { id: "inter", heading: "Inter", body: "Inter", label: "Inter" },
      { creativity: 95, atsScore: 65 }
    ),
  },
  {
    slug: "brutalist-bold",
    id: "tpl-brutalist-bold",
    name: "Brutalist Bold",
    category: "Creative",
    premium: true,
    atsOptimized: false,
    layout: "single-column",
    designLanguage: "Hard edges, massive typography",
    industry: ["Design", "Media", "Architecture"],
    colors: {
      primary: "#eab308",
      accent: "#eab308",
      background: "#ffffff",
      text: "#000000",
      muted: "#404040",
    },
    fonts: { heading: "Arial Black", body: "Arial" },
    designTheme: theme(
      "brutalist-bold",
      "Brutalist Bold",
      "brutalist",
      {
        id: "bb-palette",
        name: "Brutal",
        primary: "#000000",
        secondary: "#eab308",
        accent: "#eab308",
        background: "#ffffff",
        surface: "#f5f5f5",
        text: "#000000",
        textMuted: "#404040",
        tags: ["bold"],
      },
      { id: "arial", heading: "Arial Black", body: "Arial", label: "Arial" },
      { creativity: 98, atsScore: 55, effects: { ...baseEffects, borderRadius: 0 } }
    ),
  },
  {
    slug: "timeline-resume",
    id: "tpl-timeline-resume",
    name: "Timeline Resume",
    category: "Modern",
    premium: false,
    atsOptimized: true,
    layout: "timeline",
    designLanguage: "Vertical timeline with date column",
    industry: ["Technology", "Project Management"],
    colors: {
      primary: "#0f766e",
      accent: "#14b8a6",
      background: "#ffffff",
      text: "#134e4a",
      muted: "#5eead4",
    },
    fonts: { heading: "Inter", body: "Inter" },
    designTheme: theme(
      "timeline-resume",
      "Timeline Resume",
      "startup",
      {
        id: "tr-palette",
        name: "Teal",
        primary: "#0f766e",
        secondary: "#14b8a6",
        accent: "#14b8a6",
        background: "#ffffff",
        surface: "#f0fdfa",
        text: "#134e4a",
        textMuted: "#64748b",
        tags: ["timeline"],
      },
      { id: "inter", heading: "Inter", body: "Inter", label: "Inter" },
      { modernity: 90, atsScore: 88 }
    ),
  },
  {
    slug: "apple-minimal",
    id: "tpl-apple-minimal",
    name: "Apple Minimal",
    category: "Modern",
    premium: true,
    atsOptimized: true,
    layout: "single-column",
    designLanguage: "Massive whitespace Apple-style",
    industry: ["Product", "Design", "Technology"],
    colors: {
      primary: "#1d1d1f",
      accent: "#86868b",
      background: "#ffffff",
      text: "#1d1d1f",
      muted: "#86868b",
    },
    fonts: { heading: "Inter", body: "Inter" },
    designTheme: theme(
      "apple-minimal",
      "Apple Minimal",
      "minimal",
      {
        id: "am-palette",
        name: "Apple",
        primary: "#1d1d1f",
        secondary: "#86868b",
        accent: "#86868b",
        background: "#ffffff",
        surface: "#fbfbfd",
        text: "#1d1d1f",
        textMuted: "#86868b",
        tags: ["apple"],
      },
      { id: "inter", heading: "Inter", body: "Inter", label: "Inter" },
      { minimalism: 98, atsScore: 92, spacing: 32, density: "spacious" }
    ),
  },
  {
    slug: "neon-cyber",
    id: "tpl-neon-cyber",
    name: "Neon Cyber",
    category: "Creative",
    premium: true,
    atsOptimized: false,
    layout: "two-column",
    designLanguage: "Cyberpunk dark gradient neon glow",
    industry: ["Engineering", "AI", "Gaming"],
    colors: {
      primary: "#a855f7",
      accent: "#22d3ee",
      background: "linear-gradient(160deg, #0f0f23 0%, #1a0a2e 50%, #0d1b2a 100%)",
      text: "#e4e4e7",
      muted: "#71717a",
    },
    fonts: { heading: "Inter", body: "Courier New" },
    designTheme: theme(
      "neon-cyber",
      "Neon Cyber",
      "cyber",
      {
        id: "nc-palette",
        name: "Cyber",
        primary: "#a855f7",
        secondary: "#22d3ee",
        accent: "#22d3ee",
        background: "#0f0f23",
        surface: "#1a0a2e",
        text: "#e4e4e7",
        textMuted: "#71717a",
        gradient: "linear-gradient(160deg, #0f0f23, #1a0a2e, #0d1b2a)",
        tags: ["cyber"],
      },
      { id: "mono", heading: "Inter", body: "Courier New", label: "Mono" },
      { mode: "dark", creativity: 96, atsScore: 50, effects: { ...baseEffects, glow: true } }
    ),
  },
  {
    slug: "glassmorphism",
    id: "tpl-glassmorphism",
    name: "Glassmorphism",
    category: "Modern",
    premium: true,
    atsOptimized: false,
    layout: "card-grid",
    designLanguage: "Floating blur glass cards on gradient",
    industry: ["Design", "UI/UX", "Product"],
    colors: {
      primary: "#6366f1",
      accent: "#ec4899",
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)",
      text: "#1e1b4b",
      muted: "#64748b",
    },
    fonts: { heading: "Inter", body: "Inter" },
    designTheme: theme(
      "glassmorphism",
      "Glassmorphism",
      "glass",
      {
        id: "gl-palette",
        name: "Glass",
        primary: "#6366f1",
        secondary: "#ec4899",
        accent: "#ec4899",
        background: "#667eea",
        surface: "rgba(255,255,255,0.2)",
        text: "#1e1b4b",
        textMuted: "#64748b",
        gradient: "linear-gradient(135deg, #667eea, #764ba2, #f093fb)",
        tags: ["glass"],
      },
      { id: "inter", heading: "Inter", body: "Inter", label: "Inter" },
      { creativity: 90, effects: { ...baseEffects, blur: 12, glassOpacity: 0.25 } }
    ),
  },
  {
    slug: "magazine-editorial",
    id: "tpl-magazine-editorial",
    name: "Magazine Editorial",
    category: "Creative",
    premium: true,
    atsOptimized: false,
    layout: "two-column",
    designLanguage: "Newspaper editorial two-column grid",
    industry: ["Media", "Publishing", "Journalism"],
    colors: {
      primary: "#1c1917",
      accent: "#78716c",
      background: "#fafaf9",
      text: "#1c1917",
      muted: "#78716c",
    },
    fonts: { heading: "Georgia", body: "Georgia" },
    designTheme: theme(
      "magazine-editorial",
      "Magazine Editorial",
      "creative",
      {
        id: "me-palette",
        name: "Editorial",
        primary: "#1c1917",
        secondary: "#78716c",
        accent: "#78716c",
        background: "#fafaf9",
        surface: "#f5f5f4",
        text: "#1c1917",
        textMuted: "#78716c",
        tags: ["editorial"],
      },
      { id: "georgia", heading: "Georgia", body: "Georgia", label: "Georgia" },
      { creativity: 88, atsScore: 70 }
    ),
  },
  {
    slug: "canva-creative",
    id: "tpl-canva-creative",
    name: "Canva Creative",
    category: "Creative",
    premium: true,
    atsOptimized: false,
    layout: "card-grid",
    designLanguage: "Infographic colorful skill bars",
    industry: ["Marketing", "Creative", "Social Media"],
    colors: {
      primary: "#2563eb",
      accent: "#f97316",
      background: "#ffffff",
      text: "#1e293b",
      muted: "#64748b",
    },
    fonts: { heading: "Inter", body: "Inter" },
    designTheme: theme(
      "canva-creative",
      "Canva Creative",
      "creative",
      {
        id: "cc-palette",
        name: "Canva",
        primary: "#2563eb",
        secondary: "#f97316",
        accent: "#f97316",
        background: "#ffffff",
        surface: "#f8fafc",
        text: "#1e293b",
        textMuted: "#64748b",
        tags: ["infographic"],
      },
      { id: "inter", heading: "Inter", body: "Inter", label: "Inter" },
      { creativity: 97, modernity: 94 }
    ),
  },
  {
    slug: "ats-ultra-professional",
    id: "tpl-ats-ultra",
    name: "ATS Ultra Professional",
    category: "Professional",
    premium: false,
    atsOptimized: true,
    layout: "single-column",
    designLanguage: "Plain text maximum ATS parsing",
    industry: ["All Industries", "Government", "Healthcare"],
    colors: {
      primary: "#000000",
      accent: "#000000",
      background: "#ffffff",
      text: "#222222",
      muted: "#555555",
    },
    fonts: { heading: "Arial", body: "Arial" },
    designTheme: theme(
      "ats-ultra-professional",
      "ATS Ultra Professional",
      "faang",
      {
        id: "ats-palette",
        name: "Plain",
        primary: "#000000",
        secondary: "#333333",
        accent: "#000000",
        background: "#ffffff",
        surface: "#ffffff",
        text: "#222222",
        textMuted: "#555555",
        tags: ["ats"],
      },
      { id: "arial", heading: "Arial", body: "Arial", label: "Arial" },
      { atsScore: 99, minimalism: 99, creativity: 5 }
    ),
  },
  {
    slug: "sunset-gradient",
    id: "tpl-sunset-gradient",
    name: "Sunset Gradient",
    category: "Creative",
    premium: false,
    atsOptimized: false,
    layout: "card-grid",
    designLanguage: "Coral-to-violet gradient hero with floating card layout",
    industry: ["Design", "Marketing", "Social Media", "Startup"],
    colors: {
      primary: "#ff6b6b",
      accent: "#f06595",
      background: "#fff5f5",
      text: "#2d3436",
      muted: "#636e72",
      surface: "#ffffff",
    },
    fonts: { heading: "Poppins", body: "DM Sans" },
    designTheme: theme(
      "sunset-gradient",
      "Sunset Gradient",
      "creative",
      {
        id: "sg-palette",
        name: "Sunset",
        primary: "#ff6b6b",
        secondary: "#f06595",
        accent: "#845ef7",
        background: "#fff5f5",
        surface: "#ffffff",
        text: "#2d3436",
        textMuted: "#636e72",
        gradient: "linear-gradient(135deg, #ff6b6b, #f06595, #845ef7)",
        tags: ["gradient", "creative", "modern"],
      },
      { id: "poppins", heading: "Poppins", body: "DM Sans", label: "Poppins" },
      { creativity: 96, modernity: 94, atsScore: 68 }
    ),
  },
  {
    slug: "swiss-international",
    id: "tpl-swiss-international",
    name: "Swiss International",
    category: "Creative",
    premium: false,
    atsOptimized: true,
    layout: "single-column",
    designLanguage: "Swiss poster grid — red spine, yellow accent, numbered sections",
    industry: ["Design", "Architecture", "Media", "Advertising"],
    colors: {
      primary: "#e63946",
      accent: "#ffd166",
      background: "#ffffff",
      text: "#1d1d1f",
      muted: "#6b7280",
      surface: "#f5f5f4",
    },
    fonts: { heading: "Inter", body: "Inter" },
    designTheme: theme(
      "swiss-international",
      "Swiss International",
      "brutalist",
      {
        id: "si-palette",
        name: "Swiss",
        primary: "#e63946",
        secondary: "#1d1d1f",
        accent: "#ffd166",
        background: "#ffffff",
        surface: "#f5f5f4",
        text: "#1d1d1f",
        textMuted: "#6b7280",
        tags: ["swiss", "poster", "bold"],
      },
      { id: "inter", heading: "Inter", body: "Inter", label: "Inter" },
      { creativity: 92, minimalism: 75, atsScore: 82, effects: { ...baseEffects, borderRadius: 0 } }
    ),
  },
  {
    slug: "art-deco-luxe",
    id: "tpl-art-deco-luxe",
    name: "Art Deco Luxe",
    category: "Executive",
    premium: true,
    atsOptimized: false,
    layout: "single-column",
    designLanguage: "Navy & gold Gatsby frame with geometric art-deco ornaments",
    industry: ["Hospitality", "Luxury", "Events", "Executive"],
    colors: {
      primary: "#0c1929",
      accent: "#d4af37",
      background: "#0c1929",
      text: "#f5f0e6",
      muted: "#a89f91",
    },
    fonts: { heading: "Playfair Display", body: "Cormorant Garamond" },
    designTheme: theme(
      "art-deco-luxe",
      "Art Deco Luxe",
      "luxury",
      {
        id: "ad-palette",
        name: "Art Deco",
        primary: "#0c1929",
        secondary: "#1a2f4a",
        accent: "#d4af37",
        background: "#0c1929",
        surface: "#142238",
        text: "#f5f0e6",
        textMuted: "#a89f91",
        tags: ["luxury", "gold", "deco"],
      },
      { id: "playfair", heading: "Playfair Display", body: "Cormorant Garamond", label: "Serif Luxe" },
      { mode: "dark", creativity: 90, atsScore: 62, effects: { ...baseEffects, glow: true } }
    ),
  },
];

export function defToEditorTemplate(def: DistinctTemplateDef): CvEditorTemplate {
  const catalog = getCatalogEntry(def.slug);
  const source: TemplateMetadata = {
    id: def.id,
    slug: def.slug,
    title: def.name,
    industry: def.industry,
    layout: def.layout,
    theme: def.designTheme,
    tags: [def.designLanguage, def.category.toLowerCase()],
    premium: def.premium,
    animated: false,
    portfolio: def.category === "Creative",
    previewGradient: `linear-gradient(145deg, ${def.colors.primary}, ${def.colors.accent})`,
    category: def.category,
  } as TemplateMetadata & { category: CoreTemplateCategory };

  return {
    id: def.id,
    name: def.name,
    category: def.category,
    thumbnail: def.slug,
    previewImage: catalog?.previewImage ?? getTemplatePreviewPath(def.slug),
    description: catalog?.description ?? def.designLanguage,
    premium: def.premium,
    atsOptimized: def.atsOptimized,
    colors: def.colors,
    fonts: def.fonts,
    layout: def.layout,
    slug: def.slug,
    source,
  };
}

export function getDistinctTemplate(slug: string): DistinctTemplateDef | undefined {
  return DISTINCT_TEMPLATES.find((t) => t.slug === slug || t.id === slug);
}
