import { A4_HEIGHT, A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Futuristic cyberpunk — dark gradient, neon glow accents */
export function buildNeonCyber(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  return [
    el({
      id: "bg-gradient",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: A4_HEIGHT,
      content: "",
      locked: true,
      style: {
        background: theme.background,
        borderRadius: 0,
      },
    }),
    el({
      id: "glow-top",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: 4,
      content: "",
      style: {
        background: theme.accent,
        boxShadow: `0 0 20px ${theme.accent}`,
      },
    }),
    el({
      id: "name",
      type: "text",
      x: 48,
      y: 48,
      width: 500,
      height: 44,
      content: SAMPLE.name,
      style: {
        fontSize: 32,
        fontWeight: 700,
        color: "#ffffff",
        fontFamily: fonts.heading,
        letterSpacing: 1,
        textShadow: `0 0 12px ${theme.accent}80`,
      },
    }),
    el({
      id: "title",
      type: "text",
      x: 48,
      y: 96,
      width: 400,
      height: 24,
      content: `// ${SAMPLE.title}`,
      style: {
        fontSize: 13,
        color: theme.accent,
        fontFamily: fonts.body,
        letterSpacing: 0.5,
      },
    }),
    el({
      id: "terminal-box",
      type: "section",
      x: 48,
      y: 140,
      width: A4_WIDTH - 96,
      height: 72,
      content: "",
      style: {
        background: "rgba(0,255,255,0.06)",
        border: `1px solid ${theme.accent}60`,
        borderRadius: 4,
        boxShadow: `0 0 16px ${theme.accent}30`,
      },
    }),
    el({
      id: "summary",
      type: "text",
      x: 64,
      y: 156,
      width: A4_WIDTH - 128,
      height: 48,
      content: `> ${SAMPLE.summary.slice(0, 120)}…`,
      style: {
        fontSize: 10,
        color: "#a5f3fc",
        fontFamily: fonts.body,
        lineHeight: 1.5,
      },
    }),
    el({
      id: "stats-row",
      type: "section",
      x: 48,
      y: 232,
      width: 220,
      height: 56,
      content: "",
      style: {
        border: `1px solid ${theme.primary}80`,
        borderRadius: 4,
        background: "rgba(168,85,247,0.1)",
      },
    }),
    el({
      id: "skills",
      type: "text",
      x: 60,
      y: 244,
      width: 196,
      height: 36,
      content: SAMPLE.skills.split("\n").slice(0, 3).join("\n"),
      sectionType: "skills",
      style: { fontSize: 9, color: theme.primary, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "contact-panel",
      type: "section",
      x: 284,
      y: 232,
      width: A4_WIDTH - 332,
      height: 56,
      content: "",
      style: {
        border: `1px solid ${theme.accent}40`,
        borderRadius: 4,
        background: "rgba(255,255,255,0.03)",
      },
    }),
    el({
      id: "contact",
      type: "text",
      x: 300,
      y: 248,
      width: A4_WIDTH - 364,
      height: 28,
      content: SAMPLE.contact,
      style: { fontSize: 9, color: theme.muted, fontFamily: fonts.body },
    }),
    el({
      id: "exp-label",
      type: "text",
      x: 48,
      y: 312,
      width: 200,
      height: 20,
      content: "[ EXPERIENCE ]",
      style: {
        fontSize: 11,
        fontWeight: 700,
        color: theme.accent,
        fontFamily: fonts.heading,
        letterSpacing: 2,
      },
    }),
    el({
      id: "exp-card",
      type: "section",
      x: 48,
      y: 340,
      width: A4_WIDTH - 96,
      height: 220,
      content: "",
      style: {
        border: `1px solid ${theme.primary}50`,
        borderRadius: 4,
        background: "rgba(0,0,0,0.4)",
        boxShadow: `inset 0 0 24px ${theme.primary}15`,
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: 64,
      y: 356,
      width: A4_WIDTH - 128,
      height: 188,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: { fontSize: 10, color: "#e4e4e7", fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "edu-label",
      type: "text",
      x: 48,
      y: 580,
      width: 200,
      height: 20,
      content: "[ EDUCATION ]",
      style: {
        fontSize: 11,
        fontWeight: 700,
        color: theme.accent,
        fontFamily: fonts.heading,
        letterSpacing: 2,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: 64,
      y: 608,
      width: A4_WIDTH - 128,
      height: 72,
      content: SAMPLE.education,
      sectionType: "education",
      style: { fontSize: 10, color: theme.muted, fontFamily: fonts.body, lineHeight: 1.55 },
    }),
    el({
      id: "glow-bottom",
      type: "section",
      x: 0,
      y: A4_HEIGHT - 4,
      width: A4_WIDTH,
      height: 4,
      content: "",
      style: {
        background: theme.primary,
        boxShadow: `0 0 20px ${theme.primary}`,
      },
    }),
  ];
}
