import { A4_HEIGHT, A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/**
 * Sunset Gradient — diagonal mesh hero, overlapping avatar, floating content card.
 * Inspired by modern Canva / Behance gradient portfolio CVs.
 */
export function buildSunsetGradient(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const pad = 44;
  const cardY = 200;
  const cardH = A4_HEIGHT - cardY - pad;

  return [
    el({
      id: "bg",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: A4_HEIGHT,
      content: "",
      locked: true,
      style: { background: theme.surface ?? "#fff5f5", borderRadius: 0 },
    }),
    el({
      id: "hero-gradient",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: 240,
      content: "",
      style: {
        background: `linear-gradient(135deg, ${theme.primary} 0%, ${theme.accent} 55%, #845ef7 100%)`,
        borderRadius: 0,
      },
    }),
    el({
      id: "hero-wave",
      type: "section",
      x: 0,
      y: 200,
      width: A4_WIDTH,
      height: 48,
      content: "",
      style: {
        background: theme.surface ?? "#ffffff",
        borderRadius: 32,
      },
    }),
    el({
      id: "avatar",
      type: "image",
      x: pad,
      y: 148,
      width: 108,
      height: 108,
      content: "",
      style: {
        background: "#ffffff",
        borderRadius: 999,
        boxShadow: "0 12px 40px rgba(0,0,0,0.18)",
        border: "4px solid #ffffff",
      },
    }),
    el({
      id: "name",
      type: "text",
      x: pad + 124,
      y: 168,
      width: A4_WIDTH - pad * 2 - 124,
      height: 40,
      content: SAMPLE.name,
      style: {
        fontSize: 26,
        fontWeight: 700,
        color: "#ffffff",
        fontFamily: fonts.heading,
        lineHeight: 1.1,
      },
    }),
    el({
      id: "title",
      type: "text",
      x: pad + 124,
      y: 210,
      width: 400,
      height: 24,
      content: SAMPLE.title,
      style: {
        fontSize: 13,
        color: "rgba(255,255,255,0.92)",
        fontFamily: fonts.body,
      },
    }),
    el({
      id: "contact-pill",
      type: "section",
      x: A4_WIDTH - pad - 200,
      y: 52,
      width: 200,
      height: 36,
      content: "",
      style: {
        background: "rgba(255,255,255,0.28)",
        borderRadius: 999,
      },
    }),
    el({
      id: "contact",
      type: "text",
      x: A4_WIDTH - pad - 188,
      y: 62,
      width: 176,
      height: 18,
      content: SAMPLE.contact.split("•")[0]?.trim() ?? SAMPLE.contact,
      style: {
        fontSize: 9,
        color: "#ffffff",
        fontFamily: fonts.body,
        textAlign: "center",
      },
    }),
    el({
      id: "main-card",
      type: "section",
      x: pad,
      y: cardY,
      width: A4_WIDTH - pad * 2,
      height: cardH,
      content: "",
      style: {
        background: "#ffffff",
        borderRadius: 20,
        boxShadow: "0 8px 32px rgba(255,107,107,0.12)",
      },
    }),
    el({
      id: "skills-rail",
      type: "section",
      x: pad + 16,
      y: cardY + 20,
      width: 148,
      height: cardH - 40,
      content: "",
      style: {
        background: `linear-gradient(180deg, ${theme.primary}18, ${theme.accent}12)`,
        borderRadius: 16,
      },
    }),
    el({
      id: "skills-label",
      type: "text",
      x: pad + 28,
      y: cardY + 36,
      width: 120,
      height: 16,
      content: "EXPERTISE",
      style: {
        fontSize: 9,
        fontWeight: 700,
        letterSpacing: 2,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "skills",
      type: "text",
      x: pad + 28,
      y: cardY + 58,
      width: 120,
      height: 200,
      content: SAMPLE.skills.replace(/\n/g, "\n• "),
      sectionType: "skills",
      style: {
        fontSize: 10,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 2,
      },
    }),
    el({
      id: "languages-label",
      type: "text",
      x: pad + 28,
      y: cardY + 280,
      width: 120,
      height: 16,
      content: "LANGUAGES",
      style: {
        fontSize: 9,
        fontWeight: 700,
        letterSpacing: 2,
        color: theme.accent,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "languages",
      type: "text",
      x: pad + 28,
      y: cardY + 302,
      width: 120,
      height: 80,
      content: SAMPLE.languages,
      sectionType: "languages",
      style: { fontSize: 10, color: theme.muted, fontFamily: fonts.body, lineHeight: 1.7 },
    }),
    el({
      id: "summary-label",
      type: "text",
      x: pad + 180,
      y: cardY + 28,
      width: 400,
      height: 18,
      content: "About Me",
      style: {
        fontSize: 14,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "summary",
      type: "text",
      x: pad + 180,
      y: cardY + 52,
      width: A4_WIDTH - pad - 196,
      height: 72,
      content: SAMPLE.summary,
      sectionType: "summary",
      style: {
        fontSize: 11,
        color: theme.muted,
        fontFamily: fonts.body,
        lineHeight: 1.55,
      },
    }),
    el({
      id: "exp-label",
      type: "text",
      x: pad + 180,
      y: cardY + 140,
      width: 400,
      height: 18,
      content: "Experience",
      style: {
        fontSize: 14,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "exp-accent",
      type: "section",
      x: pad + 180,
      y: cardY + 162,
      width: 48,
      height: 4,
      content: "",
      style: { background: theme.primary, borderRadius: 2 },
    }),
    el({
      id: "experience",
      type: "text",
      x: pad + 180,
      y: cardY + 174,
      width: A4_WIDTH - pad - 196,
      height: 200,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: {
        fontSize: 10,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.65,
      },
    }),
    el({
      id: "edu-label",
      type: "text",
      x: pad + 180,
      y: cardY + 390,
      width: 200,
      height: 18,
      content: "Education",
      style: {
        fontSize: 14,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: pad + 180,
      y: cardY + 414,
      width: A4_WIDTH - pad - 196,
      height: 100,
      content: SAMPLE.education,
      sectionType: "education",
      style: {
        fontSize: 10,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.6,
      },
    }),
  ];
}
