import { A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Magazine editorial — newspaper grid, serif headlines */
export function buildMagazineEditorial(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const colW = (A4_WIDTH - 96 - 24) / 2;
  const leftX = 48;
  const rightX = leftX + colW + 24;

  return [
    el({
      id: "masthead",
      type: "section",
      x: 0,
      y: 0,
      width: A4_WIDTH,
      height: 8,
      content: "",
      style: { background: theme.text },
    }),
    el({
      id: "name",
      type: "text",
      x: 48,
      y: 32,
      width: A4_WIDTH - 96,
      height: 52,
      content: SAMPLE.name,
      style: {
        fontSize: 38,
        fontWeight: 400,
        color: theme.text,
        fontFamily: fonts.heading,
        lineHeight: 1,
        fontStyle: "italic",
      },
    }),
    el({
      id: "title",
      type: "text",
      x: 48,
      y: 88,
      width: A4_WIDTH - 96,
      height: 22,
      content: SAMPLE.title,
      style: {
        fontSize: 12,
        color: theme.muted,
        fontFamily: fonts.body,
        letterSpacing: 3,
      },
    }),
    el({
      id: "rule",
      type: "section",
      x: 48,
      y: 120,
      width: A4_WIDTH - 96,
      height: 2,
      content: "",
      style: { background: theme.text },
    }),
    el({
      id: "contact",
      type: "text",
      x: 48,
      y: 132,
      width: A4_WIDTH - 96,
      height: 16,
      content: SAMPLE.contact,
      style: {
        fontSize: 9,
        color: theme.muted,
        fontFamily: fonts.body,
        textAlign: "center",
      },
    }),
    el({
      id: "lead",
      type: "text",
      x: 48,
      y: 164,
      width: A4_WIDTH - 96,
      height: 48,
      content: SAMPLE.summary,
      style: {
        fontSize: 12,
        color: theme.text,
        fontFamily: fonts.body,
        lineHeight: 1.65,
        fontStyle: "italic",
        textAlign: "center",
      },
    }),
    el({
      id: "col-divider",
      type: "section",
      x: A4_WIDTH / 2 - 1,
      y: 232,
      width: 2,
      height: 480,
      content: "",
      style: { background: theme.muted, opacity: 0.3 },
    }),
    el({
      id: "left-head",
      type: "text",
      x: leftX,
      y: 240,
      width: colW,
      height: 20,
      content: "Experience",
      style: {
        fontSize: 11,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.heading,
        letterSpacing: 2,
      },
    }),
    el({
      id: "experience",
      type: "text",
      x: leftX,
      y: 268,
      width: colW,
      height: 280,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: { fontSize: 10, color: theme.text, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "right-head",
      type: "text",
      x: rightX,
      y: 240,
      width: colW,
      height: 20,
      content: "Education & Skills",
      style: {
        fontSize: 11,
        fontWeight: 700,
        color: theme.text,
        fontFamily: fonts.heading,
        letterSpacing: 2,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: rightX,
      y: 268,
      width: colW,
      height: 120,
      content: SAMPLE.education,
      sectionType: "education",
      style: { fontSize: 10, color: theme.text, fontFamily: fonts.body, lineHeight: 1.55 },
    }),
    el({
      id: "skills",
      type: "text",
      x: rightX,
      y: 400,
      width: colW,
      height: 120,
      content: SAMPLE.skills,
      sectionType: "skills",
      style: { fontSize: 10, color: theme.muted, fontFamily: fonts.body, lineHeight: 1.7 },
    }),
    el({
      id: "footer-rule",
      type: "section",
      x: 48,
      y: 720,
      width: A4_WIDTH - 96,
      height: 1,
      content: "",
      style: { background: theme.muted, opacity: 0.4 },
    }),
    el({
      id: "footer",
      type: "text",
      x: 48,
      y: 732,
      width: A4_WIDTH - 96,
      height: 16,
      content: "References available upon request",
      style: {
        fontSize: 8,
        color: theme.muted,
        fontFamily: fonts.body,
        textAlign: "center",
        fontStyle: "italic",
      },
    }),
  ];
}
