import { A4_HEIGHT, A4_WIDTH, el, resetZIndex, SAMPLE, type TemplateFonts, type TemplateTheme } from "@/templates/shared";

/** Left sidebar + elegant two-column main */
export function buildModernSplit(theme: TemplateTheme, fonts: TemplateFonts) {
  resetZIndex();
  const sidebarW = 248;
  const pad = 40;
  const mainX = sidebarW + pad;
  const mainW = A4_WIDTH - mainX - pad;

  return [
    el({
      id: "sidebar",
      type: "section",
      x: 0,
      y: 0,
      width: sidebarW,
      height: A4_HEIGHT,
      content: "",
      style: { background: theme.primary, borderRadius: 0 },
    }),
    el({
      id: "avatar",
      type: "image",
      x: sidebarW / 2 - 56,
      y: 48,
      width: 112,
      height: 112,
      content: "",
      style: { background: theme.accent, borderRadius: 999, opacity: 0.45 },
    }),
    el({
      id: "sidebar-name",
      type: "text",
      x: 24,
      y: 176,
      width: sidebarW - 48,
      height: 48,
      content: SAMPLE.name,
      style: {
        fontSize: 18,
        fontWeight: 700,
        color: "#ffffff",
        fontFamily: fonts.heading,
        textAlign: "center",
        lineHeight: 1.2,
      },
    }),
    el({
      id: "sidebar-title",
      type: "text",
      x: 24,
      y: 228,
      width: sidebarW - 48,
      height: 36,
      content: SAMPLE.title,
      style: {
        fontSize: 11,
        color: theme.accent,
        fontFamily: fonts.body,
        textAlign: "center",
      },
    }),
    el({
      id: "sidebar-contact",
      type: "text",
      x: 24,
      y: 280,
      width: sidebarW - 48,
      height: 80,
      content: SAMPLE.contact.replace(/\s•\s/g, "\n"),
      style: {
        fontSize: 10,
        color: "rgba(255,255,255,0.85)",
        fontFamily: fonts.body,
        lineHeight: 1.7,
        textAlign: "center",
      },
    }),
    el({
      id: "skills-label",
      type: "text",
      x: 24,
      y: 380,
      width: sidebarW - 48,
      height: 18,
      content: "CORE SKILLS",
      style: {
        fontSize: 9,
        fontWeight: 700,
        letterSpacing: 2,
        color: theme.accent,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "skill-pills",
      type: "section",
      x: 24,
      y: 404,
      width: sidebarW - 48,
      height: 120,
      content: "",
      style: { background: "rgba(255,255,255,0.12)", borderRadius: 12, padding: 12 },
    }),
    el({
      id: "skills",
      type: "text",
      x: 36,
      y: 416,
      width: sidebarW - 72,
      height: 96,
      content: SAMPLE.skills,
      sectionType: "skills",
      style: {
        fontSize: 10,
        color: "#ffffff",
        fontFamily: fonts.body,
        lineHeight: 1.8,
      },
    }),
    el({
      id: "main-summary-label",
      type: "text",
      x: mainX,
      y: 48,
      width: mainW,
      height: 20,
      content: "About",
      style: {
        fontSize: 14,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "summary",
      type: "text",
      x: mainX,
      y: 76,
      width: mainW,
      height: 64,
      content: SAMPLE.summary,
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.65 },
    }),
    el({
      id: "exp-label",
      type: "text",
      x: mainX,
      y: 160,
      width: mainW,
      height: 20,
      content: "Experience",
      style: {
        fontSize: 14,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "exp-line",
      type: "section",
      x: mainX,
      y: 184,
      width: 48,
      height: 3,
      content: "",
      style: { background: theme.accent, borderRadius: 2 },
    }),
    el({
      id: "experience",
      type: "text",
      x: mainX,
      y: 200,
      width: mainW,
      height: 200,
      content: SAMPLE.experience,
      sectionType: "experience",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.6 },
    }),
    el({
      id: "edu-label",
      type: "text",
      x: mainX,
      y: 420,
      width: mainW,
      height: 20,
      content: "Education",
      style: {
        fontSize: 14,
        fontWeight: 700,
        color: theme.primary,
        fontFamily: fonts.heading,
      },
    }),
    el({
      id: "education",
      type: "text",
      x: mainX,
      y: 448,
      width: mainW,
      height: 80,
      content: SAMPLE.education,
      sectionType: "education",
      style: { fontSize: 11, color: theme.text, fontFamily: fonts.body, lineHeight: 1.55 },
    }),
  ];
}
