import path from "path";
import fs from "fs";
import nextEnv from "@next/env";
import { projectRoot } from "./project-root.mjs";

const { loadEnvConfig } = nextEnv;

const envLocalFile = path.join(projectRoot, ".env.local");

// .env.local may set NODE_ENV=production; dev scripts must load development env first.
if (process.env.npm_lifecycle_event === "dev") {
  process.env.NODE_ENV = "development";
}

const dev = process.env.NODE_ENV !== "production";

// Local dev must trust the incoming host (localhost) instead of production NEXTAUTH_URL.
if (dev) {
  process.env.AUTH_TRUST_HOST = "true";
}

if (dev && (!fs.existsSync(envLocalFile) || fs.statSync(envLocalFile).size === 0)) {
  // eslint-disable-next-line no-console
  console.warn(
    `[env] Project .env.local is missing or empty at ${envLocalFile}. ` +
      "Save your environment variables to that file so Next.js and Prisma can load them."
  );
}

// Load env from the project root. Production platforms inject vars directly.
loadEnvConfig(projectRoot, dev);

/**
 * Prisma CLI only reads `.env` / `prisma/.env` — not `.env.local`.
 * Mirror datasource URLs so `npx prisma *` works after Next.js env is loaded.
 */
function ensurePrismaDatasourceEnv() {
  const databaseUrl = process.env.DATABASE_URL?.trim();
  if (!databaseUrl) return;

  const directUrl = process.env.DIRECT_URL?.trim();
  if (!directUrl) {
    // eslint-disable-next-line no-console
    console.warn(
      "[env] DIRECT_URL is missing — Prisma migrations need db.*.supabase.co:5432 (not the pooler URL)."
    );
    return;
  }

  if (directUrl.includes("pooler.supabase.com:6543")) {
    // eslint-disable-next-line no-console
    console.warn(
      "[env] DIRECT_URL must not use pooler port 6543 — use db.*.supabase.co:5432 or session pooler :5432"
    );
  }
  const prismaEnvPath = path.join(projectRoot, "prisma", ".env");
  const body = [
    "# Generated by scripts/load-env.mjs — do not edit manually",
    "# Prisma CLI reads this file; secrets live in .env.local",
    `DATABASE_URL=${quoteEnvValue(databaseUrl)}`,
    `DIRECT_URL=${quoteEnvValue(directUrl.trim())}`,
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(prismaEnvPath), { recursive: true });
  fs.writeFileSync(prismaEnvPath, body, "utf8");
}

function quoteEnvValue(value) {
  if (/[\s#"'\\]/.test(value)) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

ensurePrismaDatasourceEnv();

export { projectRoot };
